# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena_struct.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61thena_struct.proto\x12\tathena.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb1\x01\n\rConfiguration\x12\x12\n\ncommission\x18\x01 \x01(\x01\x12\x0c\n\x04\x63\x61sh\x18\x02 \x01(\x01\x12\x14\n\x0c\x63\x61pital_risk\x18\x03 \x01(\x01\x12\x32\n\x0etrade_on_close\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x34\n\x10\x65xclusive_orders\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"\x9b\x01\n\x05Order\x12\x0c\n\x04size\x18\x01 \x01(\x01\x12\r\n\x05limit\x18\x02 \x01(\x01\x12\x0c\n\x04stop\x18\x03 \x01(\x01\x12\x11\n\tstop_loss\x18\x04 \x01(\x01\x12\x13\n\x0btake_profit\x18\x05 \x01(\x01\x12\x31\n\ris_contingent\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x0c\n\x04hash\x18\x07 \x01(\t\"\x8f\x01\n\x05Trade\x12\x0c\n\x04size\x18\x01 \x01(\x01\x12\x13\n\x0b\x65ntry_price\x18\x02 \x01(\x01\x12\x12\n\nentry_time\x18\x03 \x01(\x01\x12\x12\n\nexit_price\x18\x04 \x01(\x01\x12\x11\n\texit_time\x18\x05 \x01(\x01\x12\n\n\x02pl\x18\x06 \x01(\x01\x12\x0e\n\x06pl_ptc\x18\x07 \x01(\x01\x12\x0c\n\x04hash\x18\x08 \x01(\t\"\x84\x01\n\nStatistics\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08n_trades\x18\x03 \x01(\x03\x12\x10\n\x08win_rate\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'athena_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONFIGURATION']._serialized_start=100
  _globals['_CONFIGURATION']._serialized_end=277
  _globals['_ORDER']._serialized_start=280
  _globals['_ORDER']._serialized_end=435
  _globals['_TRADE']._serialized_start=438
  _globals['_TRADE']._serialized_end=581
  _globals['_STATISTICS']._serialized_start=584
  _globals['_STATISTICS']._serialized_end=716
# @@protoc_insertion_point(module_scope)
