# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import athena_struct_pb2 as athena__struct__pb2
import candlestick_struct_pb2 as candlestick__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61thena.proto\x12\tathena.v1\x1a\x13\x61thena_struct.proto\x1a\x18\x63\x61ndlestick_struct.proto\"b\n\x12GetBacktestRequest\x12(\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x18.athena.v1.Configuration\x12\"\n\x0c\x63\x61ndlesticks\x18\x02 \x03(\x0b\x32\x0c.Candlestick\"\x84\x01\n\x13GetBacktestResponse\x12)\n\nstatistics\x18\x01 \x01(\x0b\x32\x15.athena.v1.Statistics\x12 \n\x06orders\x18\x02 \x03(\x0b\x32\x10.athena.v1.Order\x12 \n\x06trades\x18\x03 \x03(\x0b\x32\x10.athena.v1.Trade2V\n\x06\x41thena\x12L\n\x0bGetBacktest\x12\x1d.athena.v1.GetBacktestRequest\x1a\x1e.athena.v1.GetBacktestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'athena_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBACKTESTREQUEST']._serialized_start=74
  _globals['_GETBACKTESTREQUEST']._serialized_end=172
  _globals['_GETBACKTESTRESPONSE']._serialized_start=175
  _globals['_GETBACKTESTRESPONSE']._serialized_end=307
  _globals['_ATHENA']._serialized_start=309
  _globals['_ATHENA']._serialized_end=395
# @@protoc_insertion_point(module_scope)
