# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import athena_pb2 as athena__pb2


class AthenaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBacktest = channel.unary_unary(
                '/athena.v1.Athena/GetBacktest',
                request_serializer=athena__pb2.GetBacktestRequest.SerializeToString,
                response_deserializer=athena__pb2.GetBacktestResponse.FromString,
                )


class AthenaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AthenaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktest,
                    request_deserializer=athena__pb2.GetBacktestRequest.FromString,
                    response_serializer=athena__pb2.GetBacktestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'athena.v1.Athena', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Athena(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/athena.v1.Athena/GetBacktest',
            athena__pb2.GetBacktestRequest.SerializeToString,
            athena__pb2.GetBacktestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
