# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enums_struct.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65nums_struct.proto*5\n\x08Position\x12\x14\n\x10UNKNOWN_POSITION\x10\x00\x12\x08\n\x04LONG\x10\x01\x12\t\n\x05SHORT\x10\x02*+\n\x04Side\x12\x10\n\x0cUNKNOWN_SIDE\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITION']._serialized_start=22
  _globals['_POSITION']._serialized_end=75
  _globals['_SIDE']._serialized_start=77
  _globals['_SIDE']._serialized_end=120
# @@protoc_insertion_point(module_scope)
